secrets:
  onion_address:
    file: ./hs_ed25519_secret_key

services:
  tor:
    image: goldy/tor-hidden-service
    links:
      - omeglestr
    environment:
      ONION_ADDRESS_TOR_SERVICE_HOSTS: '80:omeglestr:80'
      ONION_ADDRESS_TOR_SERVICE_VERSION: '3'

    secrets:
      - source: onion_address
        target: onion_address
        mode: 400

  omeglestr:
    image: omeglestr
    container_name: omeglestr
    build:
      context: ./.
      dockerfile: ./Dockerfile
    restart: always