services:
  omeglestr-dev:
    image: omeglestr-dev
    container_name: omeglestr-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /omeglestr
    ports:
      - "9876:9876"
      - "9229:9229"
      - "4200:4200"
    volumes:
      - ..:/omeglestr:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
