version: '3.9'

services:
  omegle-nostr-dev:
    image: omegle-nostr-dev
    container_name: omegle-nostr-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /omegle-nostr
    ports:
      - "9229:9229"
      - "4200:4200"
    volumes:
      - ..:/omegle-nostr:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=ndk:*
    tty: true
