services:
  omeglestr-dev:
    image: omeglestr-dev
    container_name: omeglestr-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /omeglestr
    ports:
      - "4222:4222"
    volumes:
      - ..:/omeglestr:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true

