version: '3.9'

services:
  relay-strfry:
    image: relay-strfry
    container_name: strfry
    build:
      context: ../.
      dockerfile: ./relay-debug/Dockerfile.relay
    ports:
      - 7777:7777
    volumes:
      - ./strfry-db:/strfry/strfry-db
      - ./strfry.conf:/etc/strfry.conf
    tty: true
  nostr-debug:
    image: nostr-debug
    container_name: nostr-debug
    ports:
      - 8077:80
    build:
      context: ../.
      dockerfile: ./relay-debug/Dockerfile.debug
    tty: true
